version: '3'
services:

  #Nginx Service
  dashboard:
    image: richarvey/nginx-php-fpm
    container_name: dashboard
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/site-enabled/default.conf
      - ./app/:/var/www/html
    ports:
      - "80:80"
      - "443:443"


